#sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-3.2.3"
sdkversion: 3.2.1
name: iUniversidade
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.iuniversidade
  BundleURLScheme: iuniversidade
wp:
  productid: '47b17930-0414-012f-15be-040cceda8b28'
symbian:
  uid: '0xea62acf0'
android:
  version: 2.1

extensions: ["json", "another-extension"]
